#!/bin/sh

rightBranch=`git status --branch --porcelain | grep -b dev`
if [ "$rightBranch" != "" ]; then
	echo "---------------------------------------------------"
	echo "Commit failed..."
	echo "You cannot directly commit into the dev branch!"
	echo "---------------------------------------------------"
	exit 1;
fi

rightBranch=`git status --branch --porcelain | grep -b test`
if [ "$rightBranch" != "" ]; then
	echo "---------------------------------------------------"
	echo "Commit failed..."
	echo "You cannot directly commit into the test branch!"
	echo "---------------------------------------------------"
	exit 1;
fi

rightBranch=`git status --branch --porcelain | grep -b prod`
if [ "$rightBranch" != "" ]; then
	echo "---------------------------------------------------"
	echo "Commit failed..."
	echo "You cannot directly commit into the prod branch!"
	echo "---------------------------------------------------"
	exit 1;
fi

hasPackageJson=`git status --branch --porcelain | grep -b package.json`
if [ "$hasPackageJson" == "" ]; then
	echo "---------------------------------------------------"
	echo "Commit failed..."
	echo "No edits in package.json! Update your version number"
	echo "4.1.x : Minor changes and bug fixes"
	echo "4.x.1 : New features and larger changes"
	echo "x.1.1 : Major new version"
	echo "---------------------------------------------------"
	exit 1;
fi

hasPackageVersionChange=`git diff-index --patch-with-stat --unified=0 HEAD package.json | grep -b '\"version\"'`
if [ "$hasPackageVersionChange" == "" ]; then
	echo "---------------------------------------------------"
	echo "Commit failed..."
	echo "You've not updated the package version!"
	echo "4.1.x : Minor changes and bug fixes"
	echo "4.x.1 : New features and larger changes"
	echo "x.1.1 : Major new version"
	echo "---------------------------------------------------"
	exit 1
fi

exit 0
